### ISSUE TITLE
Long startup flags are being cut

### ISSUE THREAD

**Issue by FokaStudio** [PufferPanel/PufferPanel#1010]
I have a server and I tried to use aikar's flags for it, but for some reason it always cuts it to about half of the initial flags

**Comment by john-f-chamberlain** [comment]
Since you provided very little information ( Please refer to: https://github.com/PufferPanel/PufferPanel/blob/master/.github/CONTRIBUTING.md ), I assume you're referring to:
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

If so, I am unable to reproduce this issue.
I have the Run Configuration > Command on the template set to: 
```
java -Xms${memory}M -Xmx${memory}M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar purpurclip.jar nogui
```
None of which gets cut off because it wouldn't run otherwise ( the jar is listed last )

**Comment by FokaStudio** [comment]
The issue occured when I have pasted the flags in and reloaded the page
idk if that will help

and no, I don't mean in the templates, I have pasted them into the 'Edit Server Definition'

**Comment by FokaStudio** [comment]
Closing due to the fact that it got fixed somehow, I don't know what has actually happened there
