### ISSUE TITLE
Laggy behaviour when long or simultaneous log records appear in Console

### ISSUE THREAD

**Issue by shoker537** [PufferPanel/PufferPanel#1014]
So I have some plugins that need to log lots of lines (also appears with exceptions).
For example, I use a world management plugin. It loads 10 worlds when starting the server, all they have to be printed out with their settings (a bunch of lines). So my server is already working and these lines are already printed out by the server console, but are still printing by the panel (it also delays futher logs, that have to be already printed too).

It also breaks the browser page, it stops responding and can't be refreshed for a while.

**Comment by nepcore** [comment]
I noticed that I must have at some point accidentally removed a bit of code that gives the page time to render when a lot of messages come in in fast succession and already fixed that together with some other console improvements in 650f5cd9590fa79008411716b685178500e90f6c, therefore this will be fixed in the next release

**Comment by shoker537** [comment]
Thank you very much! ♥
