### ISSUE TITLE
Ram not degrading?

### ISSUE THREAD

**Issue by Blueeyestar** [PufferPanel/PufferPanel#1147]
Good day,
I installed the great panel today.

It's really great and has a lot of features.
Unfortunately, only one thing doesn't do it. It doesn't deplete the ram again when the server is empty. It always stays on the graphic from the last highest.
Should that be so?
![Unbenannt](https://user-images.githubusercontent.com/35557302/161655433-4a785298-d22a-4de1-a1c1-cb56af60ee04.png)

**Comment by nepcore** [comment]
PufferPanel doesn't actually mess with the memory usage of servers, it just looks at the resources the process is using and displays that, some software just deallocate resources, that may be a bug or by design, for example java starts with a smallish memory footprint, but whenever it needs more it'll take what it needs up to the defined limit and holds onto those resources because asking the OS for more is an expensive thing to do and if you just hold on to what you have already you don't need to ask for those resources again, so a java process in PufferPanel would look like it's always just using more and more memory when in truth most of that could be unused, the JVM just isn't releasing that memory (that is a bit oversimplified, java _does_ deallocate memory under certain conditions, but it is very reluctant about it)

**Comment by Blueeyestar** [comment]
Thank you for the useful information. So I just ignore the ad.
Otherwise the panel works really well. I'm always surprised what treasures can be found in the open source.
A really great panel
