### ISSUE TITLE
[FEATURE] Logs buffer

### ISSUE THREAD

**Issue by pierrbt** [PufferPanel/PufferPanel#1193]
Each time we refresh the console, the panel only load few lines, and we don't see old logs, it would be nice to see all the logs since startup or make a button at the top to load more because view only 20 last logs rows is not really usefull ! And if it doesn't already exists, add a file which contains ALL the logs since server creation.

**Comment by nepcore** [comment]
PufferPanel holds what is retained between reloads in memory, as such holding too much per server will negatively impact the host server performance  
Keeping all logs in files can easily cause performance bottlenecks as well, especially on HDDs, but even SSDs won't keep up long if enough servers hammer out console lines at high enough rates  
A single file containing the entire log history of a server will also quickly grow so unwieldy it's useless as you'll quickly have trouble even searching in the file  
Additionally, such log files would often end up hardly readable (or searchable) due to how things like for example colored output work  
Also, a lot of software already brings options to write log files (free of color codes etc) to disk and rotate them occasionally, which can cover needing to look back further than what is in the console

**Comment by pierrbt** [comment]
But the number of loaded lines is really low, can't we increase it (maybe in config)

**Comment by LordRalex** [comment]
In the config for the node, it would be daemon.console.buffer, where the .'s are a new JSON object. 50 is the default.

```json
{
  "daemon": {
    "console": {
      "buffer": 50
    }
  }
