### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by pierrbt** [PufferPanel/PufferPanel#1203]
**Describe the bug**
I get my server overloaded by players and then it crashed, but like it wasn't really stopped but in crashing state, it wasn't restarting. Could you make that it detect crashing (via debug or thread dump file) and then kill it tkt restart it ?

**To Reproduce**
1. Overload the server
2. Wait it crashes
3. And then it do not restart

**Expected behavior**
It should restart

**Screenshots**
![Screenshot_2022-10-02-12-17-59-292_com.discord.jpg](https://user-images.githubusercontent.com/83456236/193449307-e8e4e9ad-f18e-429e-8410-90331048f6ba.jpg)

**Desktop (please complete the following information):**
 - OS: Debian 11

**Comment by LordRalex** [comment]
Detecting if it hung is basically impossible, and is up to the server software to handle. This isn't something I'd like for the panel to support, because it's very unique to each and every type of software, and it'd be very difficult to do. It is just better to configure your software such that it kills the server (which vanilla already does anyways). Then, autorecovery can kick in and restart it.
