### ISSUE TITLE
Your session timed out, please log in again

### ISSUE THREAD

**Issue by FurmigaHumana** [PufferPanel/PufferPanel#1210]
**Describe the bug**
I keep getting disconnected with the message "Your session timed out, please log in again" right after login, the server list wont even finish loading and it already disconnects.

No errors in any of the log files, only a bunch of "Panel key pulled from" on the daemon log, If I quickly open a server while the server list is loading I can stay connected for longer and use the console just fine, but if I try to edit any server settings it will disconnect me.

After a few tries it will stay connected for some time, are sessions attached to the ip address? If so thats probably the case since my ip changes randomly due to my reverse proxy configuration, an option to allow ip changes in the session would suffice.

**To Reproduce**
1. Open the panel
2. Log in
3. Wait a few seconds
4. Disconnected!

**Expected behavior**
Keep my session alive for some time

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - Version 107

**Additional context**
I have two identical nodes, both running Ubuntu 22.04 on the same network, it appears the session will remain alive just fine if I am using the servers on the local node, but as soon as I try to edit the server settings (console works fine) in any of the servers running on the other node, it will disconnect.

**Comment by LexFuturorum** [comment]
Check if the system time is correctly set

**Comment by FurmigaHumana** [comment]
> Check if the system time is correctly set

it is

**Comment by NiklasRosenkranz** [comment]
i got an issue like that when my second note crashed and couldnt connect again

**Comment by FurmigaHumana** [comment]
A update on this.. after a month of usage and a few reboots the problem seems to have solved itself, I imagine something got confused while I was setting up nodes and changing several configurations all at once but it seems to have figured itself out. I know how awful it is to debug issues without knowing how to reproduce them so I guess if this goes stale and no one else complains about it the issue can be closed at will :)

**Comment by bucketmouse** [comment]
I've got the same issue. Installing under YunoHost on Debian 10/x64 causes this instantly - the second you log in you're logged out for inactivity and dropped back to the login prompt.

I've tried reinstalling several times as well as rebooting.

**Comment by notzune** [comment]
From reading these comments it seems to support my suspicion that this error is caused when something happens to the configuration file of one of your nodes.

Started happening to me after I updated pufferpanel on my node machine and overwrote the pufferpanel config file.

**Comment by notzune** [comment]
For anyone else that gets this issue and is looking for a fix until this issue is patched, this is how I was able to fix it:

Follow these steps:

1. Stop pufferpanel on both machines (``systemctl stop pufferpanel``)

### ON YOUR MAIN SERVER (the one hosting the 'local' pufferpanel):

2. go to your pufferpanel folder located at /var/lib/pufferpanel
3. locate a file called "database.db" and open it **
4. delete the records for the `remote` node which had its config file changed or corrupted in the `nodes` table **
5. delete the records for any server that was being hosted on the `remote` node in the `servers` table **
6. start pufferpanel on your `local` machine and open pufferpanel and go to nodes > add node (the +) and re-add your remote node and replace the config.json with the one they gave you on your remote node
7. start pufferpanel on your `remote` machine

refresh the pufferpanel and everything should be working fine! hope this helped!

**(I used [DB Browser for SQLite](https://sqlitebrowser.org/), if you are also using DB Browser for the first time then follow these steps:)
1. In the top menu Open database -> database.db
2. In the left window "Browse data" -> Table `nodes` -> right click on the number signifying the record for your `remote node` -> "Delete record"
3. Repeat steps for records in the `servers` table

**Comment by FurmigaHumana** [comment]
I haven't touched my setup since and still operating fine, but im pending an update which I think I can do in a few days, I will try messing with the settings see if that it what triggers it.
