### ISSUE TITLE
Add support for a use of a security key with 2FA

### ISSUE THREAD

**Issue by Lunascaped** [PufferPanel/PufferPanel#1216]
I've been selfhosting pufferpanel on my server for a while now and I love it so far, the fact it offers 2FA is awesome. However I use a security key for a lot of my services instead of just 2FA for convince sake, I was wondering if there were any plans to add support for use of a security key when signing in so I don't have to pull my phone out and open my 2Factor app every time I want to login to Pufferpanel, would much rather pull out my keys and plug my key in. Thank you all for the work you do on this amazing project.

**Comment by nepcore** [comment]
I definitely see the benefit of hardware tokens, I use them myself in most places, but as I described in #1202 the problem is implementation being not an easy thing and most people not even using TOTP, let alone even considering hardware tokens  
Please put anything you want to add on the topic into #1202 so it's all in one place rather than being strewn across a million different issues/discussions/whatever and getting lost
