### ISSUE TITLE
Uploading folders using the file manager

### ISSUE THREAD

**Issue by Cerealistic** [PufferPanel/PufferPanel#1262]
**Is your feature request related to a problem? Please describe.**
I cannot upload any folders to the file manager, and SFTP doesn't work.

**Describe the solution you'd like**
To be able to upload folders to the file manager.

**Describe alternatives you've considered**
There are no alternatives to this.

**Comment by disconsented** [comment]
What are the permissions of the server folder/files?

PufferPanel needs to own these, and tampering with them manually frequently leads to breakages like this.

**Comment by Cerealistic** [comment]
I have installed pufferpanel and it has created the files, but I wish to upload my own folders to the file manager. It should own the server files, but I want to replace them with my own.

**Comment by disconsented** [comment]
The SFTP implementation is reliable, any breakages are likely from tampering with files, running the panel in an unsupported manner or _rarely_ an unsupported client.

For support issues, [join the discord](https://discord.gg/v8dz49e).

**Comment by nepcore** [comment]
Just to make it clear, the web file manager does not support folders and probably will not any time soon. Browsers are not good at file handling in the best of cases and completely insane in the worst. Uploading a folder is completely unsupported by browsers and even letting a user select a folder is only somewhat possible in non-standard ways bringing along tons of headaches.

The built in SFTP exists because browsers are bad at being file managers and it usually works perfectly fine so long as no firewall is blocking the port (5657 by default) and you copy the credentials from the panel correctly.

**Comment by Cerealistic** [comment]
> Just to make it clear, the web file manager does not support folders and probably will not any time soon. Browsers are not good at file handling in the best of cases and completely insane in the worst. Uploading a folder is completely unsupported by browsers and even letting a user select a folder is only somewhat possible in non-standard ways bringing along tons of headaches.
> 
> The built in SFTP exists because browsers are bad at being file managers and it usually works perfectly fine so long as no firewall is blocking the port (5657 by default) and you copy the credentials from the panel correctly.

I tried to use SFTP, but I get an error that my password is invalid. I use my panel password.
