### ISSUE TITLE
ARM build for Docker image

### ISSUE THREAD

**Issue by justapieop** [PufferPanel/PufferPanel#1274]
**Is your feature request related to a problem? Please describe.**
Clearly, the standard installation states that PufferPanel supports Linux (in my case it's Ubuntu 22.04) with ARM64 architecture but the published Docker images does not. 

**Describe the solution you'd like**
Add the ARM64 into the supported architectures in Github Action workflow files if possible.

**Describe alternatives you've considered**
I tried Pterodactyl but I really want something that can run standalone on Docker without installing additional packages like PufferPanel.

**Additional context**
No.

**Comment by nepcore** [comment]
The documentations states support specifically on the page regarding [installation as an OS package](https://docs.pufferpanel.com/en/latest/installing.html), the entirely separate page regarding [installation as a Docker container](https://docs.pufferpanel.com/en/latest/installing-docker.html) makes no mentions to anything regarding ARM

As previously pointed out by @LordRalex [here](https://github.com/PufferPanel/PufferPanel/issues/1059#issuecomment-1166688262) GitHub Actions does not offer ARM based runners and Dockers crossbuilding solution is basically spinning up a VM which, due to the architecture mismatch between host and guest, runs so slow that it times out our builds

You can certainly build an ARM image yourself by following the GitHub Actions workflows on your own system, though it'd be a lot easier to simply install PufferPanel as an OS package and run the servers you create within it in their own Docker containers by using the [Docker environment](https://docs.pufferpanel.com/en/latest/environments/docker.html)

And given that an issue already exists for this I will close this one as a duplicate
