### ISSUE TITLE
Scroll bar with bookmarks

### ISSUE THREAD

**Issue by elBelgg** [PufferPanel/PufferPanel#1302]
**Is your feature request related to a problem? Please describe.**
No, it's just aesthetic. On the server administration screen, if browser bookmarks are always activated, a scroll bar will be added.

**Describe the solution you'd like**
I would like that if I always have the bookmarks activated, a scroll bar would not be added since it gets a little annoying.

**Comment by nepcore** [comment]
This has for quite a while already been the case in the currently in development 3.0 version of PufferPanel, though this is not yet released I'll close this issue since the work is already done and just waiting to be released

2.x will probably not get that change due to development focus having shifted to getting 3.0 to release as well as 2.x using a different UI component library that, due to how we're using it, makes this a decent bit harder than one might assume it would be to just scale the console height relative to the viewport height
