### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by JustRed23** [PufferPanel/PufferPanel#1338]
**Is your feature request related to a problem? Please describe.**
The current contributing page on the pufferpanel site is outdated, specifying build options for v2, not for v3

**Describe the solution you'd like**
Could you maybe add a v2/v3 toggle for updated documentation

**Describe alternatives you've considered**
An alternative would be to add a quick setup section to the README on github

**Additional context**
.

**Comment by nepcore** [comment]
The v3 documentation isn't linked in the RTD version switcher because v3 is currently still in alpha, as such at least in my opinion it's also not wrong for the docs to still be providing the building instructions for v2, the docs repo has a branch for v3 where that should be updated eventually, though the changes between v2 and v3 regarding building aren't all that much if I remember correctly, but feel free to point out anything you notice being out of date, as developing on a project for a long time can certainly cause you to grow blind to such changes

**Comment by JustRed23** [comment]
Got it, thanks!
