### ISSUE TITLE
Control servers using API

### ISSUE THREAD

**Issue by drtweety** [PufferPanel/PufferPanel#400]
We should be able to perform actions like start, stop, restart and get player data from a minecraft server

**Comment by koo04** [comment]
As in from a remote site/whatever or from the game itself?

**Comment by worldmc** [comment]
I like this idea,  I would integrate this into a costum page on the web center that we are building.  However it does need proper protection.

**Comment by koo04** [comment]
There is an API already being put in place, if that is what we are talking about. #164

**Comment by drtweety** [comment]
I know it is not in a functional form yet, but can we expect this to come into existense?

**Comment by DaneEveritt** [comment]
Yes, that is why the enhancement and api labels were attached to the issue. We are taking it slow with this update because of other things happening in life, as well as our focus on improving backend code as we move along. Wether or not this feature ships with 0.8.0, or with a later release... who knows.

**Comment by puffrfish** [comment]
While the API won't be ready for 0.8.0, it will be implemented in some form in 0.8.1. Thank you for your patience with this highly requested feature! Closing since progress should go in #164
