### ISSUE TITLE
Show user password in API

### ISSUE THREAD

**Issue by drtweety** [PufferPanel/PufferPanel#408]
I am currently working on an API module and wish to allow PufferPanel to handle all the users. So, for logging in, I will need the user's password to be displayed.

**Comment by Deaygo** [comment]
I assume you mean being able to use PufferPanel as the login mechanism for your system.  The passwords would be salted and not able to be shown.

**Comment by drtweety** [comment]
Ok, but at least can I get the salted value? Since I can encrypt the user input password and compare it with the one on file?

**Comment by Deaygo** [comment]
Perhaps a better option would be to be able to verify the password via an API call.  Of course, the implementation would be entirely up to @DaneEveritt.

**Comment by DaneEveritt** [comment]
There is no way to return the user's password through the API, and even if there was I would not do that since it opens up the potential for attacks using the API. I can make it so that you can pass an email and password and the API can return true/false if the combo is valid, but for security purposes their password will not be sent to you in the API.

Additionally, you cannot externally hash user passwords since the entire mechanism relies on blowfish hashing using a key that is stored on the server itself and randomly generated salts.

**Comment by SonarBeserk** [comment]
Likely would be smart to implement some throttling or add a setting when auth keys are implemented to limit this functionality. Otherwise you have a real nice way to do a mass password check.

**Comment by drtweety** [comment]
Fine, then atleast can we make a request with the username and password so that we get a true or false value as you told in your response?

**Comment by DaneEveritt** [comment]
We sure can.

**Comment by drtweety** [comment]
Thanks! hope to get this feature ASAP!

**Comment by drtweety** [comment]
Any ETA?

**Comment by DaneEveritt** [comment]
I've been fairly busy with college, and so have a lot of the other developers. It will come... Soon™

**Comment by LordRalex** [comment]
As a note to this, since the API is external, a throttle or limit when you have "internal" apps using it is asking for trouble. With that, we probably would have to look at how to tackle that issue as well, since we don't want just an abuse on the api caller locking it out completely.
