### ISSUE TITLE
Ip adress in the panel shown. Should be the FQDN instead

### ISSUE THREAD

**Issue by Maelstrom96** [PufferPanel/PufferPanel#456]
As a host, I was just curious, why do you offer to write the FQDN if you don't show it anywere ? I think it would be nice for the user to see, if it is set, the FQDN instead of the plane IP of the node. This would need to be a FQDN per IP instead of per node.

http://i.gyazo.com/20a8cabcb0cf5b664fa6306e804cc0cf.png

**Comment by puffrfish** [comment]
I believe the node's FQDN is meant to be used internally. Since we would only be able to have one FQDN for each IP (many hosts have multiple servers on one IP), I think it's better if this is done with #142. That way users or hosts could set DNS records to their liking, and it could appear in the list in a user specific manner.

**Comment by DaneEveritt** [comment]
This probably just slipped through the cracks. It is implemented, mostly for viewing purposes, so it should be displaying in more places.

**Comment by DaneEveritt** [comment]
Ignore me, @puffrfish has the right idea here.

**Comment by DaneEveritt** [comment]
Closing this issue for now. FQDN is now used throughout the panel to make calls to Scales since we need it to use signed SSL certificates.
