### ISSUE TITLE
Update a Server

### ISSUE THREAD

**Issue by computerwizjared** [PufferPanel/PufferPanel#518]
It would be great if you could implement server JAR updating. For example, if I am running Spigot, it will automatically run BuildTools again and then restart the server. By the way, I was very impressed when I saw the auto-install functionality (BuildTools integration) :+1:

**Comment by Wargog** [comment]
Or, to avoid using resources for every you've got running BuildTools every time there is an update, you could set up a tool or plugin that sets it up sort of like a local repository that each server can just grab the jar from a single source.

**Comment by DaneEveritt** [comment]
@computerwizjared — its in the pipeline to do re-installs and plugin changes, hopefully not too far away.

@Wargog — that I something I have been considering for awhile now, possibly by doing `SHA1` hashes of files to check for changes. The problem with BuildTools is more that it is just a wrapper for building the `spigot.jar` from remote sources, so I'd need to hook into some type of API to monitor for changes. I agree though, it is a super slow process that should be sped up.

Part of the logic for downloading things each time, even for SRCDS, was to keep everything up to date, however since these scripts are all open source, if you have any ideas for better implementations I'd love to hear them.

**Comment by computerwizjared** [comment]
@DaneEveritt You could even make a fork of BuildTools just for PufferPanel if you wanted.

**Comment by DaneEveritt** [comment]
BuildTools doesn't really change, its their git repos that do, BuildTools just compiles the patches.

**Comment by Wargog** [comment]
There could be some sort of Maven integration, I don't know much about it but I think there is some support for updates to files in the way you would need there. You also could set up something with the API that checks the Spigot repo for updates as well.

**Comment by DaneEveritt** [comment]
Support added for this. Reinstalls entire server, does not just update a single jar. If you want that you'll have to do it manually.
