### ISSUE TITLE
"Installer Progress" tab causes Chrome tab to freeze

### ISSUE THREAD

**Issue by computerwizjared** [PufferPanel/PufferPanel#526]
When I go to install Spigot, it will start installing, but after 30 seconds or so, the tab I have open with the install progress freezes. I must close and reopen that tab to make it work again. It will occasionally freeze again even after I've closed and reopened it. I'm assuming that it has something to do with BuildTools generating a lot of text for the console to spit out. This may not be fixable, but I just wanted to point it out.

**Comment by DaneEveritt** [comment]
Can confirm this issue, it appears that is is because of the amount of data being thrown out to the socket. Unfortunately there isn't really any clean way to prevent this, although it doesn't have this behavior in Safari, so I think it is more how chrome handles the websockets, it appears that the data keeps coming even after refreshing the page, and it tries to load the socket even before the page is done loading, so everything just queues up behind it while trying to load.

**Comment by topjor** [comment]
I can confirm this issue also on opera, sometimes it crashes the page on install.
I also have that sometimes the page just goes to a hang on console, and have to refresh the page

**Comment by DaneEveritt** [comment]
Thanks for the report. Like before, this is probably due to the amount of data being spewed out by the socket. I believe the simplest fix would actually just be limiting the amount of data stored on the page in the textarea box by removing lines as new ones are added.

**Comment by ET-Bent** [comment]
Sound plausible. I will love this fix in the new version. There is no problem when data is thrown in over hours in the pack. The problem only occurs when loads of "data" / lines come in, in the curse of a few seconds. 

(Google Chrome 44.0.2403.157 (64-bit))

**Comment by DaneEveritt** [comment]
Yeah, unfortunately there is only so much I can do to fix the issue right now. I am looking at options for preventing it in the future, but nothing will really happen until 0.9 is released.

**Comment by Omeryl** [comment]
While mitigated, it's not completely fixed.
