### ISSUE TITLE
Installer sets MySQL-User wrong

### ISSUE THREAD

**Issue by Paktosan** [PufferPanel/PufferPanel#538]
If you tell the installer to use a remote MySQL-Server it sets the pufferpanel-user to localhost only. This results in the panel being unable to access the database.

**Comment by LordRalex** [comment]
This is a known caveat with the installer. It would be quite difficult to code the installer in such an automated way to determine the correct host to permit access to the database without compromising security on the account.

As this is an installer-specific bug, and has no relation to the panel itself, I will ask that you create this on the Tools so that it can be tracked there: https://github.com/PufferPanel/Tools

**Comment by LordRalex** [comment]
Noting for future reference: select host from information_schema.processlist WHERE ID=connection_id(); should work out for this, just going to be fun passing that data back

**Comment by Paktosan** [comment]
Ok, I moved it to the correct tracker.

**Comment by LordRalex** [comment]
Thanks, closing now to track on https://github.com/PufferPanel/Tools/issues/8
