### ISSUE TITLE
Custom theme support

### ISSUE THREAD

**Issue by LordRalex** [PufferPanel/PufferPanel#549]
To support changing themes as it is, the panel requires you to make changes to certain files, and then execute a `git update-index --assume-unchanged` command, to which is not documented on our panel.

It would be better if the panel directly supported custom themes in the form of a /themes/ folder, and allow for custom CSS to be used, and possibly allow users to select the theme they want to use.

(ref: https://community.pufferpanel.com/topic/66-my-theme-for-pufferpanel/)

**Comment by Zendrex** [comment]
I actually did more then just the CSS. I also edited the html files a little. If you want my changes, let me know.

**Comment by LordRalex** [comment]
@Zendrex then yes, I would like to know what you did,  as that will help decide how I need to handle this

**Comment by Zendrex** [comment]
I removed from both base html files the following:

<a class="navbar-brand" href="/index">{{ settings.company_name }}</a>
This was because I put the logo above and not int he header/navbar.

I then edited <ul class="nav navbar-nav">
Changed it to: <ul class="nav navbar-nav" style="background-color: #F8F8F8">
(I dont remember if this was needed after my css edits, but its one of the changes from the two files (one backup, other main site)

**Comment by DaneEveritt** [comment]
I feel like this is going to be an issue regardless of implementation especially if there are HTML changes that a user makes. I think a good way to do this would be the themes folder which isn't affected by updates, but also providing a listing of changes to each HTML file that would make upgrades easier. That, or store them as mini templates that can be overridden by the themes folder so that upgrades don't have as noticeable of an impact on the theme...

**Comment by LordRalex** [comment]
@DaneEveritt "It would be better if the panel directly supported custom themes in the form of a /themes/ folder, and allow for custom CSS to be used, and possibly allow users to select the theme they want to use."

Pretty much already planned on doing something like that.
