### ISSUE TITLE
Alter permissions to allow locking the file manager to specified directories

### ISSUE THREAD

**Issue by SonarBeserk** [PufferPanel/PufferPanel#554]
Im working on my own implementation of this but would appreciate any help possible.

The intention is if you only want a user to do things like maybe change config files or the world files but not delete things you didnt intend them to touch. Also would allow if done right locking a server to only changing the world which is why I want it. My intentions should never require a user to alter anything but the world.

**Comment by SonarBeserk** [comment]
The way I would intend for things to work is the scales permission s:files would become s:files:* to represent all files and the former behavior. But also to have a check for something like s:files:dir which could be extended to s:files:dir:name or just have dir be the name of the directory. The issue is the need to alter the permissions manager, which im having trouble locating for one.

**Comment by DaneEveritt** [comment]
I feel likes this could be done with a JSON file that Scales reads from whenever a file is being edited. This would make checking a lot quicker and reduce the amount of permissions nodes that we would need to keep track of. It would also make it really quick and easy to update the permissions on the fly without having to shit there and manually edit permissions, as well as make implementation a million times easier. We could also get more advanced with it since it is JSON and make it so you can only edit xyz in a folder and z in a different folder.

**Comment by LordRalex** [comment]
I think the concept of permissions really need to be handled first before we try to tackle this. Permissions are horrible at the time, and so it would need a good system there before we could do this,
