### ISSUE TITLE
Everything

### ISSUE THREAD

**Issue by ShayBox** [PufferPanel/PufferPanel#594]
FUCK You, your panel sucks. ive had to re-install my Server and lost all my files because of your panel.   first i lost apache configs and it wouldn't load then because you configured ufw to enable, i couldn't login to ssh. and even after re-installing my server os and setting up the panel. i don't know the URL redirect to get TO the panel. my /var/www directory is empty

**Comment by BlueFreakLP** [comment]
You dont read the Description.....
And you are a bad system admin too:
* You dont read the installer Script
* You dont done Backups?
* You are too stupid to configure your ssh server and look if its running before
you close your current session?

Dont blame others for your fails. PufferPanel is great....




On So., Aug. 09, 2015 at 2:37 Nachm., ShayBox < notifications@github.com [notifications@github.com] > wrote:
FUCK You, your panel sucks. ive had to re-install my Server and lost all my
files because of your panel. first i lost apache configs and it wouldn't load
then because you configured ufw to enable, i couldn't login to ssh. and even
after re-installing my server os and setting up the panel. i don't know the URL
redirect to get TO the panel. my /var/www directory is empty

**Comment by BlameDylan** [comment]
Whoa, that hurts. These developers spend their presous time developing this awesome panel, at no cost to you. If you asked in a more polite matter, I would be more than happy to assist you. Your should seriously read the license:

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

This is clearly user error, and I can tell you are defiantly exaggerating. Go buy multicraft and think about what you've said. Bye.

**Comment by ShayBox** [comment]
i dont have to be polite when i just lost all my server files because of a panel. that still doesnt work mind you. i followed every step on the docs. Nowhere does it say what url its instaleld under. domain.com/panel would be nice, but they isnt one

**Comment by BlameDylan** [comment]
@ShayBox you don't even deserve help.

**Comment by ShayBox** [comment]
im not asking for help, im telling you to fix your panel so this doesnt happen to anyone else.

**Comment by ShayBox** [comment]
ive already switched to SpaceCP private beta

**Comment by BlameDylan** [comment]
Lol, these are crazy problems. I never dealed with them. Enough is enough.

**Comment by turtledude01** [comment]
Your complaining that you lost everything due to this pannel, when actually you lost your things due to your own error, no one else has ever had an issue that caused them to reinstall the OS.

**Comment by ShayBox** [comment]
i followed the instructions, i left the install location default. i added the commit to the apache2.conf and installed scales. nothing works

**Comment by turtledude01** [comment]
I would try to help you now, but you were soo rude before, have fun.  A little kindness goes a long way

**Comment by ShayBox** [comment]
well, fyi to anyone else trying to use this panel, wait until its fixed only like 30 people have used this panel. i recommend SpaceCP, Multicraft, or Spacebukkit. its better than loosing your data. and noone even cares. im sure they would care if it was there data.

**Comment by turtledude01** [comment]
I've installed this panel myself many times.  I've never had an issue.  If you read through the installation instructions, and do what they say, you'll be fine.  And I'm sure more than 30 people use this panel.  And once again, it is not broken.

**Comment by DaneEveritt** [comment]
If you had taken the time to read all of the documentation and take advantage of the multiple methods of support that we offer I'm sure you could have gotten the panel working properly. We are always welcome to constructive criticism and are more than willing to look at our documentation and change things to make it easier to understand (which happens fairly regularly), and we also throughly check that the documentation and installer scripts work on the systems that we list as being supported.

There is no process in the panel installation that would delete files from your server (that weren't installed by the panel), nor is there a process that would break SSH logins unless you just copy and paste code without reading what it says to do with it.

Everything you did that broke your server was *your* doing, not the fault of any other person or the panel in any way. Just because we say to do something doesn't mean that you should just do it blindly, common sense would dictate that enabling a firewall would also require opening up ports for other services, including SSH.
