### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by GeARCraft1** [PufferPanel/PufferPanel#607]
Hi! I was trying to install PufferPanel on Windows Server 2012 R2 when I noticed that the installer was for Linux, so now I want to help to offer windows support. I have advanced PowerShell ( like Linux sh for windows) knowledges and an copy of Advanced Installer Architect, so I just need to know how to install it on windows. Any Idea???

**Comment by Omeryl** [comment]
The Scales daemon doesn't have support for Windows, and nobody has any
interest of porting as far as I know.

**Comment by puffrfish** [comment]
While we do not plan to support Windows for PufferPanel v0.9.0, we are experimenting with getting Scales to run on Windows to support Windows-only game servers. Please join us on IRC (irc.esper.net #pufferpanel) if you have nodejs experience and would like to help us with that. Otherwise, please stay tuned!

**Comment by GeARCraft1** [comment]
I think is possible to run the hydra branch on windows, running rethinkdb in a VM

**Comment by puffrfish** [comment]
I agree it is possible, but not something we are going to be supporting as improving the ease of installation is a huge reason for our current refactoring. Perhaps in the future, but I don't see much of a reason why PufferPanel (the web interface itself) would need to run on Windows when you could also just run PufferPanel in a VM as well.
