### ISSUE TITLE
Two-Factor Authentication don't work

### ISSUE THREAD

**Issue by xion87** [PufferPanel/PufferPanel#610]
I just tried to use this feature by using google authenticator, it say "Unable to verify your TOTP token. Please try again." when i insert the number code...

**Comment by DaneEveritt** [comment]
It sounds like it is something on your end with the authenticator application that is causing issues because this was well tested and works fine on plenty of other installs. It is completely independent of the panel in terms of authentication, so I would venture to say that for some reason the authenticator app is generating something wrong. Have you tried Duo Mobile?

**Comment by puffrfish** [comment]
Since the TOTP token is time based, make sure the time on your device and your server are accurate.

**Comment by xion87** [comment]
Is true, TOTP token it work but the google one don't work... lol

**Comment by Omeryl** [comment]
I've tested this with Google Authenticator, Authy, and Duo (when I still used them). As long as your times are in sync, it would work.
