### ISSUE TITLE
No Formatting on pages/images 

### ISSUE THREAD

**Issue by IH8Sn0wFal** [PufferPanel/PufferPanel#650]
CentOS 6.7, Same thing happens with Ubuntu 14.04, installs perfect, but web interface has no images, or any kind of formatting.  

![s](https://cloud.githubusercontent.com/assets/5621468/11831401/025cee36-a374-11e5-939e-2841021c582f.PNG)

**Comment by Omeryl** [comment]
Are you using an SSL certificate with your panel?

Go into admin/general settings and tick "Require SSL connection" so that the assets url is updated.

**Comment by IH8Sn0wFal** [comment]
i am not currenclty using an ssl cert or HTTPS

**Comment by myiume** [comment]
This happens due to the fact that your URL settings are misconfigured.

In order to fix this:

1.Login your administrator account.
[img]http://i.imgur.com/U8xBV6D.png[/img]

2.Go to Admin Control Panel
[img]http://i.imgur.com/xLWfTin.png[/img]

3.Go to URL Settings
[img]http://i.imgur.com/kNUyW8c.png[/img]

4.Set the URLs to the appropriate URLs. If you changed the port of your panel from default 80, make sure to reflect that into your URL.
[img]http://i.imgur.com/fi2JCGi.png[/img]

Voila. It now loads the CSS.
