### ISSUE TITLE
Redirect to HTTPS

### ISSUE THREAD

**Issue by blazerunner44** [PufferPanel/PufferPanel#676]
I've installed Pufferpannel and followed the guide to setup a letsencrypt certificate. I checked the setting box that said "Require Secure Connection" in the panel global settings. Underneath that checkbox it says requests to the panel from a non-secure connection will redirect, however I am still able to access the panel using http:// as well as https://. Is there something else I need to do to redirect http requests to https?

![image](https://cloud.githubusercontent.com/assets/12058167/13338852/6c5b9346-dbe1-11e5-8a02-8ec88a74478c.png)

**Comment by LordRalex** [comment]
It looks like at some point we broke that setting's meaning, and had it not actually force that redirect. Since I already have to do another release to fix a bug that could occur on some systems, I can see if I can re-add this code back in if it does not take long.

**Comment by LordRalex** [comment]
Having looked into the code, I now recall why we removed it.

Cloudflare is why. If you use their SSL service, the panel would receive those connections over HTTP, but since you configured the panel to only use HTTPS (so it thinks), it's going to endlessly loop. I'd have to rewrite how the logic worked to detect Cloudflare in order for it to correctly work.

**Comment by blazerunner44** [comment]
If I were to want to enable this on my panel where would I insert the code? I'm assuming somewhere in /srv/pufferpanel ?

**Comment by LordRalex** [comment]
You would want Nginx to be handling that to reduce overall load

http://serverfault.com/questions/67316/in-nginx-how-can-i-rewrite-all-http-requests-to-https-while-maintaining-sub-dom
