### ISSUE TITLE
Support installation in a subdirectory

### ISSUE THREAD

**Issue by RunasSudo** [PufferPanel/PufferPanel#687]
PufferPanel 0.7 could be configured to be accessed from a subdirectory (e.g. https://example.com/pufferpanel/), however PufferPanel 0.8 fails for a variety of reasons in this situation, even when "PufferPanel Master URL" is set correctly.

From what I can see, in order to resolve the issue,
1. The notes on [this page](https://github.com/klein/klein.php/wiki/Sub-Directory-Installation) must be implemented.
2. Calls to `$response->redirect` must be modified to take into account the subdirectory, or Klein itself patched to do so.
3. Links in _app/views_ must be modified to take into account the subdirectory.

**Comment by puffrfish** [comment]
I appreciate your research into this, however I'm not sure this is worth the effort seeing as the current codebase is frozen and people can use a subdomain (panel.example.com). That being said, I have seen a few people tripped up by this and I will make an exception for this (since it is a major usability issue) if a satisfactory pull request is submitted.

In addition to the items you've specified I would like to see the installer have an option for this so that the nginx pufferpanel.conf is automatically configured correctly.

**Comment by LordRalex** [comment]
Re-tackling this issue if someone wanted to PR a fix:

Instead of relying on Klein, we should have proxied out calls like this to a simpler "function", which would handle piecing the entire URL together. The second trick is to do the same with the JS files, and proxy it out to a similar method.

function redirectTo($targetRelative) {
  targetURL = $baseUrl + '/' + $targetRelative
  redirect->targetUrl
}

**Comment by GaneshKandu** [comment]
Hi
i Want to Install PufferPanel in Sub Directory ie. [http://domain/subdir](http://domain/subdir)
but PufferPanel  is redirect to [http://domain/index](http://domain/index)

**Comment by TakeMeNL** [comment]
I just took a brief look and we can detect if there is a subdir in the url and based on that go further. 
But i can also understand if we want it to be configurable.

**Comment by LordRalex** [comment]
There's several ways it could be solved, but none of the solutions are really great without some form of manual intervention by the user, or a "hope" method which just uses relative url pages (i.e .../auth/login).

That said, we do already have a custom response variable as part of 1.0, so part of the work was already done behind the scenes. The issues with lie within the javascript and all the HTML that uses it. 
(https://github.com/PufferPanel/PufferPanel/blob/master/src/core/ppresponse.php#L41 is the PHP code we'd need to alter). 

We can just strip the actual URL off and get the sub folder from the master url, then apply that as the "base" url. Same can be done on the JS, just passing that value from the php code to the js code.

The fun part will be fixing every place we reference a link....

**Comment by TakeMeNL** [comment]
Fixing every link is not a big deal here because of twig and we can trick klein.
But the problem i'm having now is
If you install the panel in `<URL>/pufferpanel/` the public dir is `<URL>/pufferpanel/public/` thats a whole other issue because the .httacces that says how it should look is in the `<URL>/pufferpanel/public/`
How are you going to map the <URL>/pufferpanel/auth/login then?

Maybe i'm just stupid :P just throwing things here.
My solution was to give Klein a 'App' class with the baseUrl in it. Then you can use that in the above file (https://github.com/PufferPanel/PufferPanel/blob/master/src/core/ppresponse.php) and other places where needed. Also giving the baseUrl to twig as global var. but with tailing slash.

**Comment by LordRalex** [comment]
There's actually a second issue I forgot about:

Klein doesn't handle sub-directories correctly, so when we do the path change, we'd see the sub, and all routes would start having issues. That's going to be effectively what you'd see with the apache issue.

https://github.com/klein/klein.php/wiki/Sub-Directory-Installation indicates methods to get around that issue

**Comment by TakeMeNL** [comment]
I'm currently working on a fix for this but requires the files to be somewhere else. 
https://github.com/TakeMeNL/PufferPanel/tree/fixes-687

**Comment by JoeJoeTV** [comment]
Is this ever going to happen?

**Comment by igiteam** [comment]
I'd like to reopen this issue because subdirectory support is still completely broken in PufferPanel v3, especially when using the official Docker image.

What I'm trying to do:
Install PufferPanel at https://mydomain.com/pufferpanel/ (subdirectory), not a subdomain.

What happens:
    The HTML loads but assets (JS/CSS) return 404 because they're requested from /js/... instead of /pufferpanel/js/...
    The panel is unusable because JavaScript modules are blocked due to MIME type errors (receiving HTML instead of JS)
    Setting masterUrl to https://mydomain.com/pufferpanel in config.json does NOT fix asset paths

Why subdomains aren't an option:
    My platform uses a reverse proxy architecture where ALL apps are under the same domain as subpaths (/app1, /app2, /pufferpanel)
    Adding a subdomain breaks the unified architecture and requires separate SSL certificates
    Many users (including myself) need this for corporate/internal deployments where wildcard certificates aren't available

What needs to be fixed:
    Frontend build needs to support a configurable base path (like Vite's base option)
    Asset paths in the compiled HTML must be prefixed with the subdirectory
    The Go binary's embedded filesystem needs to serve assets from the correct subpath
    Routing must respect the subdirectory prefix

This is a significant blocker for anyone trying to integrate PufferPanel into an existing domain structure.

Please reopen and prioritize this issue. The current "just use a subdomain" workaround is not acceptable for many production deployments.

I'm willing to test PRs if someone can implement this properly.

**Comment by disconsented** [comment]
Subdirectories are not broken, they're (probably) just not supported, and they're a defunct way of approaching this kind of problem.

As for your specific reasoning:

>  My platform uses a reverse proxy architecture where ALL apps are under the same domain as subpaths (/app1, /app2, /pufferpanel)

This is an artificial limitation on your end, not an actual hard requirement.

>  Adding a subdomain breaks the unified architecture and requires separate SSL certificates

"Unified architecture" is at best a subjective interpretation here, and like you noted, wildcard certificates are a thing. However, given the prevalence of ACME clients these days (certbot and friends), with how flexible they are, I'm not convinced this is a credible argument today.

>  Many users (including myself) need this for corporate/internal deployments where wildcard certificates aren't available

This isn't an enterprise product, we're not likely to find that to be a particularly compelling argument here. Its also just not a popular request, having last cropped up in the discord in 2024 https://discord.com/channels/291396338141364226/291396338141364226/1300523063833792573

On top of this, there are other, more practical advantages:

- Stronger isolation, cookies and friends won't be shared, lowering the surface area of attacks (extra important given the prevalence of supply chain attacks these days).
- Better flexibility for configuring reverse proxies.
- It also subjectively reads as more "mature".

**Comment by igiteam** [comment]
Please, I'm begging you.

I just want to play Operation Flashpoint multiplayer with my friends.

I've spent days trying to get PufferPanel working at /pufferpanel so it fits into my reverse proxy setup. I've tried everything. I can't make it work. And now I find out it's just not supported.

Every other app I use works in a subdirectory. Forgejo does. VSCode does. Even Mumble does. Only PufferPanel refuses.

Please, please compile a new version with subpath support. Just set the base path to /pufferpanel/ and rebuild. Or tell me exactly what files to change so I can do it myself.

I'm not a developer. I just want to host Operation Flashpoint servers for me and my friends. Your panel is the only one that can do what I need, but without subdirectory support, I can't use it.

I'm literally begging you. Please help me make this work.

I will test anything. I will use any beta version. I just want to play the game.

Please.

**Comment by LexFuturorum** [comment]
as it looks to me if you wanna do it yourself, you have to change all the urls in the client and rewrite the path to pufferpanel using your prefered webserver, although i agree with disconsented, this is a bad idea, and with all in one tools like nginx proxy manager its even more hussle than a new subdomain.

**Comment by disconsented** [comment]
My advice here is to go down the happy path, get another domain if you have some weird restriction there w/ tunnelling, DynDNS or whatever you need to make that side work.

Given that you can install PP, you can install Certbot or something functionally equivalent, and, you can swap to a functioning reverse proxy if that's somehow a limitation.

Hey @nepcore or @LordRalex, can we please lock this?
