### ISSUE TITLE
The minecraft plugin is a bit outdated and a bit broken.

### ISSUE THREAD

**Issue by akiva3577** [PufferPanel/PufferPanel#692]
Im running a clean install of scales and the automatic server setup is a bit broken.
First the server port is not forced into the server.properties files, allowing 2 things to happen.
The server wont startup and no logs are shown because the logs are enabled to show after the server startup was successful. and people can choose their own port because the control panel is not forcing the port.
the spigot installation is outdated and broken. i suggest changing the install method to something more like in the file i included.
I also included a little extra line to auto accept the minecraft EULA.
[minecraft.txt](https://github.com/PufferPanel/PufferPanel/files/229108/minecraft.txt)

**Comment by puffrfish** [comment]
The server port should be forced into the server.properties file, if this is not happening it is a bug with Scales.

I don't think it is appropriate for us to provide a system that automatically downloads pre-built Spigot jars. The buildtools method is a stretch in the first place and it's debatable if even that should be there. As a free and open source project we have to respect the rights of others, as we expect others to respect our rights.

We cannot auto-accept the EULA due to obvious legal reasons.

**Comment by akiva3577** [comment]
hmm, it may just be me. ill make a secondary server to test it. but about getting the spigot build, its getting the source build from the official page. its using the same method to downloading vanilla minecraft but getting it from the official spigot Jenkins page.
