### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by BirkhoffLee** [PufferPanel/PufferPanel#786]
Sorry, though this issue tracker is only for confirmed bug reports, but I think this is a development-related issue, so I choose to put this here.

--- 
PufferPanel needs a Docker image. 

The current installation is very easy. But some people runs applications on Docker, I am one of them. It will be no pain deploying PufferPanel if there's a Docker image for it -- Docker image works exactly the same on every platform, even including Windows. Docker is very awesome, if you don't know it, please take a look at it.

I'll keep it simple: Please make a manual installation guide. Although you have a bash installer, but it does not have any explanations. If you make a manual installation guide, I can make a Docker image for you.

I'm trying to make one based on the Ubuntu image, but it's **NOT** the way to use Docker. Services (like PHP, Nginx or MySQL server) should be deployed separately for easy managing & migrating. If you're interested, see https://github.com/MineMystery/docker-pufferpanel.

**Comment by puffrfish** [comment]
We are pretty familiar with Docker, PufferPanel actually used to support Docker to run servers inside of, and we're planning on adding it back (more properly this time) as soon as possible.

The installer is admittedly not the best thing ever, but we haven't put together a manual install guide because (time) and it would be quite long and probably confusing, since much of the installer is determining what to do per each distribution. I am not against having one though, if someone would be willing to put one together.

A user on our forum made a Docker image a while ago https://github.com/KillerGoldFisch/PufferPanel 

I haven't looked too much into it, and it probably isn't the most ideal way to do things, but that might be useful for you to reference.

Essentially the installer is doing a few things:
- Creating the pufferpanel database and pufferpanel MySQL account
- Importing the database schema
- Inserting settings and defaults into the database, including the admin user
- Configuring the web server and setting permissions accordingly
- Installing the first node (the localhost node)

I would suggest you first tackle the database portions, which is the configureMysql function (creates users and database and imports schema), the configureSite function (sets the domain or IP of the panel), and the configureUser function (creates the admin user).

**Comment by BirkhoffLee** [comment]
Will do if have time. Look forward to see your Docker support.

**Comment by Xyaren** [comment]
Is there some progress regarding this feature?
I would be very interested in a solution as well.

The linked project is not updated frequently enough to be up to date.

**Comment by LordRalex** [comment]
There has not been progress, as the rewrite has been my priority at this stage. That rewrite would directly help this issue, as it removes the php and nginx requirements, but it will not be for some time.
