### ISSUE TITLE
Enable support for windows.

### ISSUE THREAD

**Issue by baxandrei** [PufferPanel/PufferPanel#823]
add posibility to add a  node on a windows PC

**Comment by Omeryl** [comment]
PRs welcome, but the entire stack was built for only Linux in mind when I was more involved.

**Comment by Wesley-VanNeck** [comment]
@Omeryl  @baxandrei  ever heared about wsl

**Comment by Omeryl** [comment]
@Wesley-VanNeck Yes, but it's not meant for production environments and at that point you might as well just be using linux .. since windows is non-free and requires licensing costs why would you buy a windows license to install this software into WSL (which may or may not even work?)... 

My point stands.

**Comment by Wesley-VanNeck** [comment]
@Omeryl  well if have pc with oem like me from were you buyed your pc and yes i know linux id free but not everybody knows how to use it

**Comment by Omeryl** [comment]
@Wesley-VanNeck This software really isn't meant for you then, man.

**Comment by Wesley-VanNeck** [comment]
@Omeryl i know how to use linux

**Comment by baxandrei** [comment]
I know how to use linux, but I prefer windows for work.

**Comment by lycano** [comment]
@baxandrei well maybe install docker for windows and run panel inside docker?
