### ISSUE TITLE
Option to unzip uploaded files

### ISSUE THREAD

**Issue by M4RKUS-11111** [PufferPanel/PufferPanel#976]
If you want to upload a world ( for example in mc ), you would have to upload it file by file. Maybe you could add an option to unzip files, so that you can upload the map as a .zip file

**Comment by InflamedSebi** [comment]
**Workaround**
There are several approaches here. You could add an additional command to the install process of the template which tries to unzip an existing "world.zip" archive from the root if present on installation, which should suffice as a workaround for now.

**Suggestion**
For a more general and generic approach I would suggest adding a "customizing" section to templates that add clickable buttons to the UI of dependent servers. More specific the "customizing" section is a list of buttons, where each of them works exactly like the "install" section, thus containing a set of given instructions to be executed when clicked.
The permission system could adapt to this dynamically and creating a permission slider for each button, or in a static single one like "use custom buttons".

In theory the 4 existing buttons (start stop kill install) could migrate to this concept if wanted, since they are more or less just a set of instructions anyway.

In addition this might even allow for basic generic backup functionality where you can setup one button to backup the important files and one to restore the latest backup. Which is template specific and free/open enough for everyone to make the own solution.

**Comment by M4RKUS-11111** [comment]
And if zip library is imported, maby the option to dowsnload a directory would be easy to add, too.

**Comment by LordRalex** [comment]
Resolved via https://github.com/PufferPanel/PufferPanel/pull/986
