### ISSUE TITLE
File Manager: Revert file/folder sorting change

### ISSUE THREAD

**Issue by dada513** [PufferPanel/PufferPanel#981]
Seems that the file manager in development builds has stopped showing folders first, then files in the web file manager. This just makes it really annoying to look for a specific file or folder. Please revert that change before the next release

**Comment by nepcore** [comment]
The sorting behaviour has changed, yes, but it should only have made it better as instead of using file size being 0 as an indicator for something being a directory it now uses the `isFile` property the backend returns, so it should actually prevent 0 size files mixing into the folders...

What OS/Browser are you using? Also, have you tried the usual clearing chaches etc?

**Comment by dada513** [comment]
Yes, I cleared cache etc and the same thing. 

OS: Ubuntu 20.04, running pufferpanel in docker in docker
Browser: Chromium Edge latest
