### ISSUE TITLE
Fedora server installation support

### ISSUE THREAD

**Issue by Maxelweb** [PufferPanel/PufferPanel#993]
Hello, I would like to know if it's possible to add Fedora Server as supported operating system. 
Otherwise, is there a way to manully install the panel without using packagecloud? 

Thanks :smiley:

**Comment by nepcore** [comment]
If i remember correctly, Fedora should be fine using CentOS packages  
You can save the packagecloud script to a file instead of piping it into a shell directly, then you can run it with os and dist set to override the os detection, not quite sure what the exact values are to use the CentOS packages, but I'd assume os should be either `centos` or `el` and dist should be `8`

Worst case there are always the build artifacts on the GitHub releases, however, those would obviously need manual work for every update
